name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  Ruby:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.6.8'
          - '2.7.5'
          - '3.1.2'

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: gemfile
          rubocop_extensions: ''
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: diff_context

      - name: Run Minitest
        run: bundle exec rake test

      # | awk -F 'Coverage' '{print $1}' > minitest-output.json
      # - name: Minitest Report
      #   uses: davegudge/minitest-report-action@v1.0.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     json-path: minitest-output.json
